### ISSUE TITLE
Error in task.py

### ISSUE THREAD

**Issue by ebelski** [ebelski/rust-copter#13]
```
python task.py demo pwm-control
error: Invalid character `{` in pkgid: `{crate}`
Traceback (most recent call last):
  File "task.py", line 165, in <module>
    args.func(args)
  File "task.py", line 114, in demo
    target = _cargo_build(crate, args.release)
  File "task.py", line 96, in _cargo_build
    subprocess.run(cmd, shell=True, check=True, env=env)
  File "C:\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cargo build --target thumbv7em-none-eabihf --release --package {crate}' returned non-zero exit status 101.
```

**Comment by mciantyre** [comment]
Which version of Python is bundled with your Anaconda distribution?

```
python --version
```

Is it yelling about the f-string interpolation character, `{`? [f-strings](https://www.python.org/dev/peps/pep-0498/) are a Python 3.6 feature.

**Comment by ebelski** [comment]
3.6.5. 

It's not passing the actual crate name, instead it's getting a literal `{crate}` in the command line

**Comment by ebelski** [comment]
I think the issue lies with line 96 in task.py?

**Comment by mciantyre** [comment]
This is a good catch! Just reproduced on `master`. But, I can't reproduce it on the `feature/esc-protocols` brach...?

**Comment by ebelski** [comment]
There was no `f` prefix in front of the string on line 93 so it should now read `    if crate:
        cmd += f" --package {crate}"`

I'm trying that to see if it works

**Comment by mciantyre** [comment]
Looks like it! Want to push a fix? Otherwise I can grab it.

I'll add some automated tests that will run

```
python task.py demo pwm-control
```

on PRs, so these kinds of bugs don't happen again.

**Comment by ebelski** [comment]
I'll push an update to the repo
