### ISSUE TITLE
Use serial communication for PWM control demo

### ISSUE THREAD

**Issue by mciantyre** [ebelski/rust-copter#8]
We're having trouble using USB comms when connecting all the motors. Use UART as the communication mechanism.

**Comment by ebelski** [comment]
Just as a follow up, I was able to get the USB comms working but it required me to plug the Power Supply into a different power outlet and plug the Teensy USB into a different USB outlet on my PC....

**Comment by ebelski** [comment]
Do we still require the ability to communicate over UART? With USB back up and running I don't have a need for it currently.

**Comment by mciantyre** [comment]
I'm happy to put this on the back burner.

I was going to implement a prototype while simultaneously settings the foundation in the embedded stack. But, if we don't need this right now, I'll hold-off on the prototyping a one-off here. We'll eventually have this from the Teensy / embedded stack.

Labeling as 'wontfix' unless we change our minds. Once this is available through our dependencies, we can remove it.

**Comment by ebelski** [comment]
Closing for now
